# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email
# traits = Trait.create([
#   { name: "Accountable",
#     is_recruiter: false
#   },
#   { name: "Attentive",
#     is_recruiter: false,
#   },
#   { name: "Benefits",
#     is_recruiter: true,
#     description: "I need the best healthcare, dental & eye coverage; I am a dare devil, you know?"
#   },
#   { name: "Clear corporate strategy",
#     is_recruiter: true,
#     description: "I need clear instruction, do NOT deviate from the said plan."
#   },
#   { name: "Coaching",
#     is_recruiter: true,
#     description: "Can I wear a purple suit with converses to the bank meeting?"
#   },
#   { name: "Communicator",
#     is_recruiter: false
#   },
#   { name: "Community Service",
#     is_recruiter: true,
#     description: "Giving back is essential, I get joy out of helping others."
#   },
#   { name: "Company name recognition",
#     is_recruiter: true,
#     description: "I work for the largest investment bank…boutique bank, that’s cool, I guess."
#   },
#   { name: "Consistent",
#     is_recruiter: false
#   },
#   { name: "Creative",
#     is_recruiter: false
#   },
#   { name: "Curious",
#     is_recruiter: false
#   },
#   { name: "Disciplined",
#     is_recruiter: false
#   },
#   { name: "Dynamic",
#     is_recruiter: false
#   },
#   { name: "Energetic",
#     is_recruiter: false
#   },
#   { name: "Entrepreneurial",
#     is_recruiter: true,
#     description: "Status quo, boring. Calculated risk and learning through failure is of utmost importance. Zuckerberg did it."
#   },
#   { name: "Ethical",
#     is_recruiter: false
#   },
#   { name: "Fiscal Compensation",
#     is_recruiter: true,
#     description: "Salary & bonus, it’s all about the benjamins."
#   },
#   { name: "Growth & Development",
#     is_recruiter: true,
#     description: "I got this far, it’s time for you to train me."
#   },
#   { name: "Hard working",
#     is_recruiter: false
#   },
#   { name: "Honest",
#     is_recruiter: false
#   },
#   { name: "Humorous",
#     is_recruiter: false
#   },
#   { name: "Independent",
#     is_recruiter: false
#   },
#   { name: "Job Recognition",
#     is_recruiter: true,
#     description: "A pat on the back every now & again would be nice."
#   },
#   { name: "Job Security",
#     is_recruiter: true,
#     description: "The way my bank is set up, I need my job for the next 36 months."
#   },
#   { name: "Meticulous",
#     is_recruiter: false
#   },
#   { name: "Organized",
#     is_recruiter: false
#   },
#   { name: "Resourceful",
#     is_recruiter: false
#   },
#   { name: "Supportive",
#     is_recruiter: false
#   },
#   { name: "Team Player",
#     is_recruiter: false
#   },
#   { name: "Tenacious",
#     is_recruiter: false
#   },
#   { name: "Vacation",
#     is_recruiter: true,
#     description: "Caribbean here I come, two Bahama Mamas please."
#   },
#   { name: "Work Life Balance",
#     is_recruiter: true,
#     description: "No emails past 8:59pm EST. Grey’s Anatomy comes on at 9."
#   },
#   { name: "Work Travel",
#     is_recruiter: true,
#     description: "Jet life on company dime, nice….skymiles nicer!"
#   }
# ])

# competencies = Competency.create([
#   { name: "Accounting" },
#   { name: "Back End Developer" },
#   { name: "Bookkeeping" },
#   { name: "Cinematography" },
#   { name: "Corporate Banking" },
#   { name: "Culinary" },
#   { name: "Cyber Security" },
#   { name: "Data Analytics" },
#   { name: "Digital Marketing" },
#   { name: "ERP" },
#   { name: "Engineering" },
#   { name: "Front End Developer" },
#   { name: "Full Stack" },
#   { name: "Graphic Design" },
#   { name: "Insurance" },
#   { name: "Investment Banking" },
#   { name: "Logistics" },
#   { name: "Marketing" },
#   { name: "Nonprofit" },
#   { name: "Professional Admin" },
#   { name: "Programming" },
#   { name: "Project Management" },
#   { name: "Public Relations" },
#   { name: "Quality Control" },
#   { name: "Quantitative" },
#   { name: "Real Estate" },
#   { name: "Recruiting" },
#   { name: "Research" },
#   { name: "Sales" },
#   { name: "Sales and Trading" },
#   { name: "Social Media" },
#   { name: "Software Development" },
#   { name: "Strategy" },
#   { name: "Tax Professional" },
#   { name: "Teaching" },
#   { name: "Technical Support" },
#   { name: "Urban Planning" },
#   { name: "Web Development" }
# ])

[
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "Education Management",
  "E-learning",
  "Electrical & Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Fishery",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology & Services",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking/Venture",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure & Travel",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Marketing & Advertising",
  "Market Research",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Device",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organization Management",
  "Oil & Energy",
  "Online Publishing",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary",
  "Printing",
  "Professional Training",
  "Program Development",
  "Public Policy",
  "Public Relations",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational",
  "Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing"
].each do |industry|
  Industry.create(name: industry)
end
